### ISSUE TITLE
ERROR: Could not build wheels for scikit-image which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by Natejacob1031** [YFOMNN/ecapture#1]
I am having problems installing ecapture. This is what came up when I tried to install it.

**Comment by eahso2000** [comment]
having the exact same issue, btw I am using Terminal on Mac, everything else seems to work except for the scikit-image

**Comment by YFOMNN** [comment]
Which python version are you using?

**Comment by YFOMNN** [comment]
Issue closed as it is solved [here](https://github.com/YFOMNN/ecapture/issues/2#issuecomment-803324800)
