### ISSUE TITLE
ERROR: Could not build wheels for scikit-image which use PEP 517 and cannot be installed directly

### ISSUE THREAD

**Issue by gaurav3278** [YFOMNN/ecapture#2]
i was installing ecapture module but it is showing error saying **error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-too
ls/** and   **ERROR: Failed building wheel for scikit-image
Failed to build scikit-image
ERROR: Could not build wheels for scikit-image which use PEP 517 and cannot be installed directly**

PLZ HELP!!!

**Comment by YFOMNN** [comment]
Which python version are you using?

**Comment by gaurav3278** [comment]
> Which python version are you using?

python 3.9

**Comment by YFOMNN** [comment]
From what I have seen, scikit does not support Python 3.9 (in Pypi) yet. Try using an older version (like python 3.7). 
You can, however, install it for python 3.9 using  `conda install -c conda-forge scikit-learn` (if you are using anaconda).

I got this information from [here](https://github.com/scikit-learn/scikit-learn/issues/18852)

**Comment by gaurav3278** [comment]
> From what I have seen, scikit does not support Python 3.9 (in Pypi) yet. Try using an older version (like python 3.7).
> You can, however, install it for python 3.9 using `conda install -c conda-forge scikit-learn` (if you are using anaconda).
> 
> I got this information from [here](https://github.com/scikit-learn/scikit-learn/issues/18852)

tqsm :)
