### ISSUE TITLE
Wont install 

### ISSUE THREAD

**Issue by ghost** [YFOMNN/ecapture#3]
ERROR: Failed building wheel for scikit-image
Failed to build scikit-image
ERROR: Could not build wheels for scikit-image which use PEP 517 and cannot be installed directly

**Comment by ghost** [comment]
What did i do wrong

**Comment by LeggySpecB** [comment]
pretty sure this is a python3.9 issue, try python 3.8, though ive had no luck personally.

**Comment by LeggySpecB** [comment]
they haven't released a version of scikit-image for python 3.9
