### ISSUE TITLE
What Resolution is used as default?

### ISSUE THREAD

**Issue by Nthingxhere** [YFOMNN/ecapture#5]
I have some other questions too:

- Will you be able to change the resolution?

- Will you be able to change the path of the saved picture (as a string or maybe with a variable for timestamps)?

- Would it possible to use a button on a keyboard to make a picture or in case of a raspberry use a value from the GPIO pins for that?

**Comment by YFOMNN** [comment]
Greetings,
You cannot change the resolution. You should however be able do the other two.  For your last question, execute the function when the value from a raspberry pi changes using an IF statement

This project is not frequently maintained and older versions like 0.0.7 could prove to be more stable. Just a heads up!

**Comment by Nthingxhere** [comment]
Okay good to know because I used the newest version from pip and when i put a path in it didn't work

amd thank you for your answer!

**Comment by Nthingxhere** [comment]
i forgor 💀
